mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
server:
  port: 8080
  servlet:
    session:
      cookie:
        domain: localhost
spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    timeout: 86400
    store-type: redis
    redis:
      namespace: spring:session